#
# Copyright 2013-2023 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: compare-sample
description: Compare sample changes
inputs:
  application-path:
    description: Application where the application should be generated.
    required: false
    default: ${{ github.workspace }}/base/app
  current-application-path:
    description: Application where the current application is located.
    required: false
    default: ${{ github.workspace }}/app
  generator-path:
    description: Generator folder relative to workspace, git checkout, npm remove, install, and link will be executed in the folder.
    required: true
  cmd:
    description: Command to generate the sample.
    required: true
outputs:
  equals:
    description: Generated source didn't changed
    value: ${{ steps.compare.outputs.equals }}
  has-changes:
    description: Generated source has changed
    value: ${{ steps.compare.outputs.has-changes }}
runs:
  using: composite
  steps:
    - name: Create paths
      run: mkdir -p ${{ inputs.application-path }}
      shell: bash
      working-directory: ${{ github.workspace }}
    - name: "MERGE: generate base"
      id: base-app
      shell: bash
      continue-on-error: true
      run: |
        set -x
        echo "::group::generate base sample log"
        npm uninstall -g
        git restore -s @~1 .
        npm install --ignore-scripts
        npm link
        cd ${{ inputs.application-path }}
        cp -a "${{ inputs.current-application-path }}/.git" "${{ inputs.application-path }}/"
        # docker-compose and kubernetes are not reproducible, copy old config
        ls "${{ inputs.current-application-path }}/docker-compose" \
          && mkdir "${{ inputs.application-path }}/docker-compose" \
          && cp "${{ inputs.current-application-path }}/docker-compose"/.yo-rc.json "${{ inputs.application-path }}/docker-compose" \
          || true
        ls "${{ inputs.current-application-path }}/kubernetes" \
          && mkdir "${{ inputs.application-path }}/kubernetes" \
          && cp "${{ inputs.current-application-path }}/kubernetes"/.yo-rc.json "${{ inputs.application-path }}/kubernetes" \
          || true
        ${{ inputs.cmd }}
        echo "::endgroup::"
      working-directory: ${{ github.workspace }}/${{ inputs.generator-path }}/
    - name: "MERGE: revert generator state"
      shell: bash
      run: |
        git reset --hard
        git clean -fd
      working-directory: ${{ github.workspace }}/${{ inputs.generator-path }}/
    - name: "MERGE: compare changes"
      id: compare
      if: steps.base-app.outcome == 'success'
      working-directory: ${{ inputs.application-path }}
      shell: bash
      run: |
        git log
        # File keystore.p12 always changes
        # File package-lock.json is not generated
        # Verify if the generated source has changed
        git add .
        echo "Showing config diff changes (won't trigger builds)"
        echo "::group::ignored changes"
        git -c color.ui=always diff -R --cached -- \
          '.yo-rc.json' '**/.yo-rc.json' \
          '*.jdl' '**/*.jdl' \
          '.gitignore' '**/.gitignore' \
          '.gitattributes' '**/.gitattributes' \
          'README.md' '**/README.md' \
          '.jhipster/**' '**/.jhipster/**'
        echo "::endgroup::"
        echo "Showing source diff changes (will trigger builds)"
        echo "::group::changes"
        git -c color.ui=always diff -R --cached --exit-code -- . \
          ':!.yo-rc.json' ':!**/.yo-rc.json' \
          ':!*.jdl' ':!**/*.jdl' \
          ':!.gitignore' ':!**/.gitignore' \
          ':!.gitattributes' ':!**/.gitattributes' \
          ':!README.md' ':!**/README.md' \
          ':!.jhipster/**' ':!**/.jhipster/**' \
          ':!package-lock.json' ':!**/package-lock.json' \
          ':!**/keystore.p12' \
          && echo "equals=true" >> $GITHUB_OUTPUT \
          || echo "has-changes=true" >> $GITHUB_OUTPUT
        echo "::endgroup::"
