name: cache-npm-dependencies
on: [push, pull_request]
jobs:
  cache-npm-dependencies-jhipster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: jhipster-actions
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/checkout@v4
        with:
          path: generator-jhipster
          repository: jhipster/generator-jhipster
          ref: main
          fetch-depth: 1
      - uses: ./jhipster-actions/cache-npm-dependencies
        with:
          generator-path: generator-jhipster
          generator-jhipster-path: generator-jhipster
  cache-npm-dependencies-blueprints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: jhipster-actions
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/checkout@v4
        with:
          path: generator-jhipster
          repository: jhipster/generator-jhipster
          ref: main
          fetch-depth: 1
      - run: npm install
        working-directory: ${{ github.workspace }}/generator-jhipster
      - uses: ./jhipster-actions/create-app-path
      - run: npm install ${{ github.workspace }}/generator-jhipster
        working-directory: ${{ github.workspace }}/app
      - uses: ./jhipster-actions/cache-npm-dependencies
        with:
          generator-path: generator-jhipster
          generator-jhipster-path: app/node_modules/generator-jhipster/dist
